import React, { ReactNode } from 'react'
import clsx from 'clsx'
import type { Metadata } from 'next'

import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { geistMono, geistSans, meila, unbounded } from '@/styles/font-config'

import './globals.css'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          meila.variable,
          unbounded.variable,
          'antialiased'
        )}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export { metadata }
export default RootLayout
